### PR TITLE
Relative lib path

### PR DESCRIPTION
**Pull request by valentindavid**
This fixes few fixed, absolute library paths. This is a problem with Compat32 because it is mounted in a different place than expected.

For Steam, it removes the need to define variable LIBGL_DRIVERS_PATH.

### CODE REVIEW

**Comment by valentindavid** [comment]
Last commit for alsa-lib is not tested yet. I will confirm it tomorrow when it is tested.

**Comment by valentindavid** [comment]
Hopefully flathub/com.valvesoftware.Steam#31 is fixed with this.

**Comment by alexlarsson** [comment]
Looks awesome. Please report if it works.

**Comment by valentindavid** [comment]
This should work now. It is ready for review.

**Comment by valentindavid** [comment]
This has been tested in combination with flathub/com.valvesoftware.Steam#34

**Comment by valentindavid** [comment]
Note that the symbolic link to ../pulseaudio was required to make the RPATH shorter than the original which is required by chrpath. Changing the rpath at linking would have required changes in libtool. That might be an interesting hack actually. But a bit more complex.

**Comment by alexlarsson** [comment]
These changes seem to have broken the kde runtime rebuild:
https://flathub.org/builds/#/builders/3/builds/664

**Comment by alexlarsson** [comment]
If you access libpulseaudio via /lib instead of /usr/lib/ then there is maybe a problem with the symlink?

**Comment by alexlarsson** [comment]
x86-64 failed too. Here is the exact failure:
```
/usr/bin/c++   -O2 -g -fstack-protector-strong -D_FORTIFY_SOURCE=2 -std=c++0x -fno-operator-names -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -fdiagnostics-color=always -pedantic -Wsuggest-override  -Wl,--enable-new-dtags -fstack-protector-strong -Wl,-z,relro,-z,now tests/CMakeFiles/knotificationrestrictionstest.dir/knotificationrestrictionstest.cpp.o tests/CMakeFiles/knotificationrestrictionstest.dir/knotificationrestrictionstest_automoc.cpp.o  -o bin/knotificationrestrictionstest  -Wl,-rpath,/run/build-runtime/knotifications/bin -rdynamic /usr/lib/libQt5Test.so.5.9.1 bin/libKF5Notifications.so.5.39.0 /usr/lib/libQt5DBus.so.5.9.1 /usr/lib/libQt5Widgets.so.5.9.1 /usr/lib/libQt5Gui.so.5.9.1 /usr/lib/libQt5Core.so.5.9.1 && :
/usr/lib/gcc/x86_64-unknown-linux/6.2.0/../../../../x86_64-unknown-linux/bin/ld: warning: libpulsecommon-10.0.so, needed by //lib/libpulse.so.0, not found (try using -rpath or -rpath-link)
```

**Comment by alexlarsson** [comment]
Seems it affects other things too:  https://flathub.org/builds/#/builders/1/builds/676

**Comment by alexlarsson** [comment]
I did some debugging, and it seems ld just doesn't handle $ORIGIN in rpaths:

```
2510  open("//lib/libpulsecommon-10.0.so", O_RDONLY) = -1 ENOENT (No such file or directory)
2510  open("//usr/lib/libpulsecommon-10.0.so", O_RDONLY) = -1 ENOENT (No such file or directory)
2510  open("/app/lib/libpulsecommon-10.0.so", O_RDONLY) = -1 ENOENT (No such file or directory)
2510  open("/usr/lib/GL/nvidia-384-69/lib/libpulsecommon-10.0.so", O_RDONLY) = -1 ENOENT (No such file or directory)
2510  open("$ORIGIN/pulseaudio/libpulsecommon-10.0.so", O_RDONLY) = -1 ENOENT (No such file or directory)
```

This seems to be an issue for others too:
https://stackoverflow.com/questions/6323603/ld-using-rpath-origin-inside-a-shared-library-recursive

**Comment by alexlarsson** [comment]
@valentindavid Maybe you could run the rpath command in cleanup-platform-commands instead? Then it will not affect the sdk, only the platform, so linking in the sdk will still work.

**Comment by valentindavid** [comment]
We can also put "-Wl,-rpath-link,/usr/lib/pulseaudio" in libpulse.pc for pkgconfig.

But I think that cleanup-platform-commands is better idea.

**Comment by valentindavid** [comment]
Though, it is a pity that things stop working when running with --devel.

**Comment by alexlarsson** [comment]
@valentindavid They will work, we only need rpath for the 32bit version, and that always uses the platform anyway.

**Comment by alexlarsson** [comment]
i mean, 32bit on 64bit. For the regular sdk, the original rpath will work, no?

**Pull request merged**
