### PR TITLE
Don't disable rawmidi in alsa-lib

### LINKED ISSUE #28: Remove --disable* from ALSA lib build
It seems that Qt framework is rebuilding ALSA lib because it needs some of the features disabled here. Any reason to keep them disabled ?

### PR DESCRIPTION
**Pull request by Barthalion**
Fixes #28.

### CODE REVIEW

**Comment by Barthalion** [comment]
I will test the build and something that needs rawmidi tomorrow.

**Comment by alexlarsson** [comment]
I already merged this: https://github.com/flatpak/freedesktop-sdk-images/pull/31

**Comment by alexlarsson** [comment]
You should be able to try it from http://sdkbuilder1.gnome.org/repo/

**Comment by Barthalion** [comment]
Oops, missed it somehow.

**Pull request closed without merging**
